//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemeBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemeBot.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نذاری بهتره.
        /// </summary>
        internal static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً عکس، گیف یا ویدیو بفرست!☝🏻.
        /// </summary>
        internal static string PleaseUploadPhoto {
            get {
                return ResourceManager.GetString("PleaseUploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حله ثبت شد!
        ///اگه بازم میم داری همینجا آپلودش کن 🤖.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایول ✔️💥
        /// ما تو پستا معمولاً آیدی تلگرام کسی که میم رو ساخته می‌نویسیم، اگه به هر دلیلی با این قضیه حال نمی‌کنی بهم بگو:.
        /// </summary>
        internal static string ThanksAndFeedback {
            get {
                return ResourceManager.GetString("ThanksAndFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///بیپ بوپ 🤖 
        ///میم بات صحبت میکنه
        /// همینجا میمتو آپلود کن که بره تو کانال @academeme واسه رأی‌گیری 
        /// 👨🏻‍⚖️👩🏻‍⚖.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نه ردیفه.
        /// </summary>
        internal static string YesPlease {
            get {
                return ResourceManager.GetString("YesPlease", resourceCulture);
            }
        }
    }
}
